import { NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";
import prisma from "@/lib/prisma";

export const dynamic = 'force-dynamic';

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const countToGenerate = 10; // Batch size of 10 to save API requests

    // 1. Fetch past interactions (ratings, pins)
    const history = await prisma.eventInteraction.findMany({
      orderBy: { createdAt: "desc" },
    });

    const guidance = searchParams.get("guidance") || "";

    // 3. Construct prompt context
    const pinned = history.filter((h: any) => h.pinned);
    const skipped = history.filter((h: any) => h.skipped);
    const liked = history.filter((h: any) => !h.pinned && !h.skipped);

    const pinnedContext = pinned.map((h: any) => `- ${h.title} (Reason: ${h.reason ?? "N/A"})`).join("\n");
    const skippedContext = skipped.map((h: any) => `- ${h.title} (Reason skipped: ${h.reason ?? "N/A"})`).join("\n");
    const likedContext = liked.map((h: any) => `- ${h.title}`).join("\n");

    const today = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });

    const prompt = `
Generate ${countToGenerate} event recommendation(s) in New York City. 

CURRENT REFERENCE DATE: ${today}.
CRITICAL: You MUST use the Google Search tool to find REAL, upcoming events. 

### EVENT CRITERIA:
1. DATE ACCURACY: All recommended events MUST take place on or after ${today}. Use exact dates (e.g., "Tuesday, March 31, 2026"). 
2. UNIQUENESS: Focus on limited-time, unique, pop-up, or one-off events (guest lectures, concerts, weekend fairs). 
3. EXCLUSIONS: Avoid permanent attractions, long-running Broadway shows, or standard tourist traps.
4. LINK INTEGRITY: Every event MUST include a verified DEEP LINK. 
   - You MUST extract the exact URL string directly from the Google Search results.
   - NEVER construct, guess, or predict a URL path (e.g., do not guess Eventbrite URL slugs). 
   - NEVER output a general homepage (like "theskint.com"). 
   - If the search results do not provide a direct, full URL to the exact event, DO NOT suggest the event.

### USER CONTEXT:
- General Guidance: "${guidance}"
- PINNED (Planned): ${pinnedContext}
- LIKED (Interests): ${likedContext}
- SKIPPED (Avoid): ${skippedContext}

### ANALYSIS RULES:
- Do NOT suggest any event titles that already appear in the user's history.
- Analyze SKIPPED events to identify negative signals.
- Use LIKED and PINNED events to find adjacent interests.
`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        temperature: 0.2, // LOWERED: crucial for exact URL strings
        responseMimeType: "application/json", // Native JSON mode
        responseSchema: {
          type: "ARRAY",
          items: {
            type: "OBJECT",
            properties: {
              id: { type: "STRING", description: "Unique string ID" },
              title: { type: "STRING" },
              description: { type: "STRING" },
              time: { type: "STRING", description: "Format: Weekday, Month Day, Year, Time" },
              search_rationale: { type: "STRING", description: "Briefly state the exact website/source where you found this event to verify it is real." },
              link: { type: "STRING", description: "The exact, unmodified URL from the search result snippet. Do not guess or construct URLs." },
              why: { type: "STRING", description: "One sentence explaining why this matches their history." }
            },
            required: ["id", "title", "description", "time", "search_rationale", "link", "why"]
          }
        },
        tools: [
          {
            googleSearch: {}
          }
        ]
      }
    });

    let text = response.text || "";
    if (typeof text !== "string") {
      text = JSON.stringify(text); // Fallback if it's already an object
    }
    
    // Strip markdown code blocks if generated by Gemini
    text = text.replace(/```json|```/g, "").trim();
    console.log("Raw Gemini Text:", text);
    
    let eventsArray: any[] = [];
    try {
      const data = JSON.parse(text);
      eventsArray = Array.isArray(data) ? data : [];
    } catch (e) {
      console.error("Model output was not valid JSON:", text);
    }
    
    console.log(`Returning ${eventsArray.length} items from Gemini (Server-side validation bypassed).`);

    return NextResponse.json(eventsArray);

  } catch (e: any) {
    console.error("Gemini Recommendations failed:", e);
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}
