import { NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import prisma from "@/lib/prisma";

export const dynamic = 'force-dynamic';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "");

export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const isSingle = searchParams.get("single") === "true";
    const countToGenerate = isSingle ? 1 : 5;

    // 1. Fetch past interactions (ratings, pins)
    const history = await prisma.eventInteraction.findMany({
      orderBy: { createdAt: "desc" },
    });

    const guidance = searchParams.get("guidance") || "";

    // 3. Construct prompt context
    const historyContext = history.map((h: any) => 
      `- ${h.title} (Rating: ${h.rating ?? "N/A"}, Reason: ${h.reason ?? "N/A"}, Pinned: ${h.pinned}, Skipped: ${h.skipped})`
    ).join("\n");

    const today = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });

    const prompt = `
Generate ${countToGenerate} event recommendation(s) in New York City. 
Current Date of Reference: ${today}. You MUST use exact dates for events (e.g. "Tuesday, March 31, 2026") instead of relative terms like "This Tuesday" or "Tomorrow".

Here is the user's general curation guidance:
"${guidance}"

Here are their past interactions for pattern weights (Exploit what they like and Explore adjacent interests):
${historyContext}

Consider the following sources of events as inspiration (pull from similar types of events or check these style listings):
- Timeout This Weekend: https://www.timeout.com/newyork/things-to-do/things-to-do-in-nyc-this-weekend 
- The Skint: https://www.theskint.com/
- Secret NYC: https://secretnyc.co/what-to-do-this-weekend-nyc/
- NYC Resistor Calendar: https://www.nycresistor.com/calendar/
- Simons Foundation Lectures, Thought Gallery, Interintellect, Center for Fiction, Grolier Club.

Output the result as a strict JSON array of objects with these exact keys: "id" (generate a unique string), "title", "description", "time", "link", and "why" (a single sentence explaining why you recommended this based on their history or guidance).
CRITICAL for "link": Only output real, verified links. Never hallucinate deep links. If you aren't 100% sure about a specific URI structure, just output the main calendar/home URL for that site from the seed list (e.g. \`https://www.theskint.com/\` or \`https://www.nycresistor.com/calendar/\`).
`;

    const model = genAI.getGenerativeModel({
      model: "gemini-2.5-flash-lite", // User requested 2.5 flash-lite
      generationConfig: {
        responseMimeType: "application/json",
      },
    });

    const result = await model.generateContent(prompt);
    let text = result.response.text();
    
    // Strip markdown code blocks if generated by Gemini
    text = text.replace(/```json/g, '').replace(/```/g, '').trim();
    
    // Safely parse JSON
    const data = JSON.parse(text);

    return NextResponse.json(data);

  } catch (e: any) {
    console.error("Gemini Recommendations failed:", e);
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}
