import { NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import prisma from "@/lib/prisma";

export const dynamic = 'force-dynamic';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "");

export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const isSingle = searchParams.get("single") === "true";
    const countToGenerate = isSingle ? 1 : 5;

    // 1. Fetch past interactions (ratings, pins)
    const history = await prisma.eventInteraction.findMany({
      orderBy: { createdAt: "desc" },
    });

    const guidance = searchParams.get("guidance") || "";

    // 3. Construct prompt context
    const pinned = history.filter((h: any) => h.pinned);
    const skipped = history.filter((h: any) => h.skipped);
    const liked = history.filter((h: any) => !h.pinned && !h.skipped);

    const pinnedContext = pinned.map((h: any) => `- ${h.title} (Reason: ${h.reason ?? "N/A"})`).join("\n");
    const skippedContext = skipped.map((h: any) => `- ${h.title} (Reason skipped: ${h.reason ?? "N/A"})`).join("\n");
    const likedContext = liked.map((h: any) => `- ${h.title}`).join("\n");

    const today = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });

    const prompt = `
Generate ${countToGenerate} event recommendation(s) in New York City. 
Current Date of Reference: ${today}. You MUST use exact dates for events (e.g. "Tuesday, March 31, 2026") instead of relative terms like "This Tuesday" or "Tomorrow". All recommended events MUST take place on or after this Reference Date. Never recommend events in the past.

CRITICAL: Focus on limited-time, unique, pop-up, or special one-off events (like a guest lecture, a specific concert, or a weekend pop-up art fair). Avoid permanent attractions, long-running static Broadway shows, or standard tourist listings (unless it's an exceptional special engagement). Focus on events that if missed, won't happen again soon!

Here is the user's general curation guidance:
"${guidance}"

Here are the events the user has PINNED (They plan to go):
${pinnedContext}

Here are the events the user has LIKED (They like the topic/category, but will not go to this specific instance):
${likedContext}

Here are the events the user has SKIPPED (They do not like these):
${skippedContext}

CRITICAL: 
1. Do NOT suggest any event titles that already appear in the history above.
2. Analyze the reasons for SKIPPED events. Do NOT recommend events with similar characteristics to those the user skipped. Use them as negative signals.
3. The LIKED events represent topics the user is interested in. Recommend more events within these topics/categories, but assume they might need different times or settings.
4. The PINNED events represent exact matches for upcoming visits. Use them to find highly adjacent interests.

CRITICAL: Do not recommend events you have already recommended before. Avoid duplicates.

Consider the following sources of events as inspiration (pull from similar types of events or check these style listings):
- Timeout This Weekend: https://www.timeout.com/newyork/things-to-do/things-to-do-in-nyc-this-weekend 
- The Skint: https://www.theskint.com/
- Secret NYC: https://secretnyc.co/what-to-do-this-weekend-nyc/
- NYC Resistor Calendar: https://www.nycresistor.com/calendar/
- Simons Foundation Lectures, Thought Gallery, Interintellect, Center for Fiction, Grolier Club.

Output the result as a strict JSON array of objects with these exact keys: "id" (generate a unique string), "title", "description", "time" (MUST use strict format: 'Weekday, Month Day, Year, Time' e.g., 'Tuesday, March 31, 2026, 7:00 PM' or 'All Day'), "link", and "why" (a single sentence explaining why you recommended this based on their history or guidance).
CRITICAL for "link": Only output real, verified DEEP links to the specific event. NEVER just output the main calendar/home URL (like \`https://www.theskint.com/\`). The URL returned must lead directly to the event page and should have some semblance to the title of the event (e.g. contains keywords from the title). If you do not have a specific deep link, do NOT suggest that event. Every suggestion must be backed by a specific event URL.
`;

    const model = genAI.getGenerativeModel({
      model: "gemini-3.1-flash-lite-preview",
      generationConfig: {
        responseMimeType: "application/json",
      },
    });

    const result = await model.generateContent(prompt);
    let text = result.response.text();
    
    // Strip markdown code blocks if generated by Gemini
    text = text.replace(/```json/g, '').replace(/```/g, '').trim();
    console.log("Raw Gemini Text:", text);
    
    // Safely parse JSON
    const data = JSON.parse(text);
    const eventsArray = Array.isArray(data) ? data : [];
    console.log(`Returning ${eventsArray.length} items from Gemini (Server-side validation bypassed).`);

    return NextResponse.json(eventsArray);

  } catch (e: any) {
    console.error("Gemini Recommendations failed:", e);
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}
